title: Gilberto Moura # your name (or website title) here
logo: "/images/IMG_9170.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Descrevo aqui alguns dos projetos que participei durante minha carreira profissional.
  <br><br>
  Com mais de 20 anos de experiência trabalhado em desenvolvimento de software e de produtos, participei de inúmeros projetos nas mais variadas áreas como saúde, ERP, jurídica, pesquisa, entre outros.
  <br><br>
  <a href="https://www.linkedin.com/in/gilbertocesarmoura/">Perfil no LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-09QZZM9J2S # your Google Analytics tracking ID here
